<?php

// This translation mapping table was been generated by L10n tools.

$lang['WEB_FORGETPWD_INDEX_k1'] = "K1";
$lang['WEB_FORGETPWD_INDEX_k2'] = "K2";
$lang['WEB_FORGETPWD_INDEX_k3'] = "K333333";
$lang['WEB_HOME_INDEX_K0'] = "K0";
?>
