<?php

// This translation mapping table was been generated by L10n tools.

$lang['MUCHIII_MEMBER_PROFILE_total_albums'] = "Total {%total_album%} album(s)";
$lang['MUCHIII_MEMBER_PROFILE_total_photos'] = "Total {%total_photo%} photo(s)";
$lang['LOGIN_you_have_to_login'] = "Please login!!";
$lang['LOGIN_logout'] = "Logout";
$lang['LOGIN_login'] = "Login";
$lang['LOGIN_welcome'] = "It's \"welcome\"!";
$lang['LOGIN_hihi'] = "Hihi";
$lang['TOOLBAR_WISHLIST'] = "Wish list";
$lang['one'] = "One";
$lang['two'] = "Two";
$lang['three'] = "Three";
$lang['hoogle'] = "Hoogle";
$lang['MIIICASA_SERVICE_name'] = "miiiCasa";
$lang['MIIICASA_UPLOAD_browse_file'] = "browse upload file";
$lang['MIIICASA_DISPLAY_create_new_folder'] = "Create A New Folder";
$lang['MIIICASA_DISPLAY_upload_photos'] = "Upload photos";
$lang['MIIICASA_DISPLAY_select_all'] = "Select all";
$lang['MIIICASA_DISPLAY_download'] = "Download";
$lang['MIIICASA_DISPLAY_delete'] = "Delete";
$lang['MIIICASA_DISPLAY_sorting'] = "Sorting";
$lang['MIIICASA_DISPLAY_sort_by_date'] = "Sort by date";
$lang['MIIICASA_DISPLAY_share'] = "Share";
$lang['MIIICASA_DISPLAY_edit'] = "Edit";
$lang['MIIICASA_INDEX_home_file_sharing'] = "Home file sharing";
?>
