<?php

// This translation mapping table was been generated by L10n tools.

$lang['WEB_FORGETPWD_INDEX_k1'] = "鑰10";
$lang['WEB_FORGETPWD_INDEX_k2'] = "鑰20";
$lang['WEB_FORGETPWD_INDEX_k3'] = "鑰333333";
$lang['WEB_HOME_INDEX_K0'] = "鑰0";
?>
