<?php

// This page category array was been generated by l10n/lang/get_page_cate.

$page_cate = array (
	'0' => array (
		'0' => array (
			'page_id' => '1',
			'page_name' => 'WEB',
			'up_page' => '0',
		),
		'1' => array (
			'page_id' => '2',
			'page_name' => 'BAR',
			'up_page' => '0',
		),
		'2' => array (
			'page_id' => '3',
			'page_name' => 'WIDGET',
			'up_page' => '0',
		),
		'3' => array (
			'page_id' => '4',
			'page_name' => 'MIIICASA',
			'up_page' => '0',
		),
	),
	'1' => array (
		'0' => array (
			'page_id' => '5',
			'page_name' => 'HOME',
			'up_page' => '1',
		),
		'1' => array (
			'page_id' => '6',
			'page_name' => 'FORGETPWD',
			'up_page' => '1',
		),
		'2' => array (
			'page_id' => '7',
			'page_name' => 'RESETPWD',
			'up_page' => '1',
		),
		'3' => array (
			'page_id' => '8',
			'page_name' => 'PROFILE',
			'up_page' => '1',
		),
		'4' => array (
			'page_id' => '9',
			'page_name' => 'TUTORIAL',
			'up_page' => '1',
		),
		'5' => array (
			'page_id' => '10',
			'page_name' => 'ALERT',
			'up_page' => '1',
		),
		'6' => array (
			'page_id' => '11',
			'page_name' => 'ACTIVITY',
			'up_page' => '1',
		),
	),
	'2' => array (
		'0' => array (
			'page_id' => '12',
			'page_name' => 'FRAMWORK',
			'up_page' => '2',
		),
		'1' => array (
			'page_id' => '13',
			'page_name' => 'ALERT',
			'up_page' => '2',
		),
	),
	'3' => array (
		'0' => array (
			'page_id' => '14',
			'page_name' => 'PROFILE',
			'up_page' => '3',
		),
		'1' => array (
			'page_id' => '15',
			'page_name' => 'GALLERY',
			'up_page' => '3',
		),
		'2' => array (
			'page_id' => '16',
			'page_name' => 'TUTORIAL',
			'up_page' => '3',
		),
		'3' => array (
			'page_id' => '17',
			'page_name' => 'SETTING',
			'up_page' => '3',
		),
	),
	'4' => array (
		'0' => array (
			'page_id' => '18',
			'page_name' => 'HOME',
			'up_page' => '4',
		),
		'1' => array (
			'page_id' => '19',
			'page_name' => 'HOMEFILESHARING',
			'up_page' => '4',
		),
		'2' => array (
			'page_id' => '20',
			'page_name' => 'MYDEVICES',
			'up_page' => '4',
		),
		'3' => array (
			'page_id' => '21',
			'page_name' => 'MYSHAREDFOLDERS',
			'up_page' => '4',
		),
		'4' => array (
			'page_id' => '22',
			'page_name' => 'PHOTO',
			'up_page' => '4',
		),
		'5' => array (
			'page_id' => '23',
			'page_name' => 'COMPONENT',
			'up_page' => '4',
		),
	),
	'5' => array (
		'0' => array (
			'page_id' => '24',
			'page_name' => 'INDEX',
			'up_page' => '5',
		),
		'1' => array (
			'page_id' => '25',
			'page_name' => 'SIGNIN',
			'up_page' => '5',
		),
		'2' => array (
			'page_id' => '26',
			'page_name' => 'SIGNUP',
			'up_page' => '5',
		),
		'3' => array (
			'page_id' => '27',
			'page_name' => 'SIGNUPOK',
			'up_page' => '5',
		),
	),
	'6' => array (
		'0' => array (
			'page_id' => '28',
			'page_name' => 'INDEX',
			'up_page' => '6',
		),
		'1' => array (
			'page_id' => '29',
			'page_name' => 'SUCCESS',
			'up_page' => '6',
		),
	),
	'7' => array (
		'0' => array (
			'page_id' => '30',
			'page_name' => 'INDEX',
			'up_page' => '7',
		),
		'1' => array (
			'page_id' => '31',
			'page_name' => 'SUCCESS',
			'up_page' => '7',
		),
	),
	'8' => array (
		'0' => array (
			'page_id' => '32',
			'page_name' => 'INDEX',
			'up_page' => '8',
		),
	),
	'9' => array (
		'0' => array (
			'page_id' => '33',
			'page_name' => 'INDEX',
			'up_page' => '9',
		),
	),
	'10' => array (
		'0' => array (
			'page_id' => '34',
			'page_name' => 'SIGNOUT',
			'up_page' => '10',
		),
	),
	'11' => array (
		'0' => array (
			'page_id' => '35',
			'page_name' => 'INDEX',
			'up_page' => '11',
		),
	),
	'14' => array (
		'0' => array (
			'page_id' => '36',
			'page_name' => 'INDEX',
			'up_page' => '14',
		),
	),
	'15' => array (
		'0' => array (
			'page_id' => '37',
			'page_name' => 'INDEX',
			'up_page' => '15',
		),
	),
	'16' => array (
		'0' => array (
			'page_id' => '38',
			'page_name' => 'INDEX',
			'up_page' => '16',
		),
	),
	'17' => array (
		'0' => array (
			'page_id' => '39',
			'page_name' => 'INDEX',
			'up_page' => '17',
		),
	),
	'18' => array (
		'0' => array (
			'page_id' => '40',
			'page_name' => 'INDEX',
			'up_page' => '18',
		),
		'1' => array (
			'page_id' => '41',
			'page_name' => 'UPDATE',
			'up_page' => '18',
		),
	),
	'22' => array (
		'0' => array (
			'page_id' => '42',
			'page_name' => 'INDEX',
			'up_page' => '22',
		),
		'1' => array (
			'page_id' => '43',
			'page_name' => 'PHOTOHOME',
			'up_page' => '22',
		),
		'2' => array (
			'page_id' => '44',
			'page_name' => 'PHOTOSUB',
			'up_page' => '22',
		),
		'3' => array (
			'page_id' => '45',
			'page_name' => 'LARGEVIEW',
			'up_page' => '22',
		),
		'4' => array (
			'page_id' => '46',
			'page_name' => 'SLIDESHOW',
			'up_page' => '22',
		),
		'5' => array (
			'page_id' => '47',
			'page_name' => 'FOLDERINFO',
			'up_page' => '22',
		),
		'6' => array (
			'page_id' => '48',
			'page_name' => 'SHAREMGMT',
			'up_page' => '22',
		),
		'7' => array (
			'page_id' => '49',
			'page_name' => 'SHARETO',
			'up_page' => '22',
		),
	),
	'23' => array (
		'0' => array (
			'page_id' => '50',
			'page_name' => 'CHANGECOVER',
			'up_page' => '23',
		),
	),
);
?>